server:
  port: 9090
spring:
  application:
    name: app-clientes
  datasource:
    url: jdbc:mysql://localhost:3306/clientes_db
    username: root
    password: Morgan95*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
